# fly.toml app configuration file generated for liftcalc-cool-bush-2100 on 2023-12-30T19:14:08-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "liftcalc"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.name_of_your_http_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/api/_health"
    port = 5500
    timeout = "10s"
    type = "http"

[env]
  RAILS_ENV="production"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
